/*-
 * Copyright (c) <year>, zhbi98, 3049824528@qq.com
 * All rights reserved.
 *
 * DISCLAIMED, IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __LS08D_ADC_DRIVE_H__
#define __LS08D_ADC_DRIVE_H__

#define LS08D_ARR_SIZE(arr) (unsigned int)(sizeof(arr) / sizeof(arr[0]))

typedef enum {
	STATE_500MHZ,
	STATE_1000MHz,
} LS08D_Speed_t;

typedef struct {
	unsigned char _phaseADC0;
	unsigned char _phaseADC1;

	unsigned char _delaultPhaseADC0;
	unsigned char _delaultPhaseADC1;

	LS08D_Speed_t _speed;
} LS08D_TypeDef;

#endif
